# Pull base image
FROM ubuntu20.04

# Set work directory
WORKDIR app

# Install dependencies
COPY requirements.txt app
RUN apt-get update && apt-get install -y python3 python3-pip libgdal-dev git vim
RUN pip install -r requirements.txt
RUN pip install --force-reinstall torch==1.10.1+cu113 --extra-index-url httpsdownload.pytorch.orgwhl

# Copy project
COPY . app